# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_core.ipynb.

# %% auto 0
__all__ = ['code_extract2']

# %% ../nbs/02_core.ipynb 3
def code_extract2(reply):
    import re
    def extract_code(reply):
        pattern = r"```python([\s\S]*?)```"
        matches = re.findall(pattern, reply)
        code = "\n\n".join(matches)
        if code:
            return code
        pattern = r"```([\s\S]*?)```"
        matches = re.findall(pattern, reply)
        code = "\n\n".join(matches)
        return code
    return extract_code(reply)
